/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcd.telas;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gabriela Mello
 */
public class RoteirosDimensionamento extends javax.swing.JFrame {

	private static final long serialVersionUID = -4024101534481059965L;

	/**
	 * Creates new form RoteirosDimensionamento
	 */
	public RoteirosDimensionamento() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		roteiroMadParaButton = new javax.swing.JButton();
		roteiroMadPreButton = new javax.swing.JButton();
		roteiroMadAcoButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		jLabel1.setText("Escolha o roteiro desejado:");

		roteiroMadParaButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		roteiroMadParaButton.setText("Madeira/Madeira - Parafusada");
		roteiroMadParaButton.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				roteiroMadParaButtonActionPerformed(evt);
			}
		});

		roteiroMadPreButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		roteiroMadPreButton.setText("Madeira/Madeira - Pregada");
		roteiroMadPreButton.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				roteiroMadPreButtonActionPerformed(evt);
			}
		});

		roteiroMadAcoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		roteiroMadAcoButton.setText("Madeira/Aço - Parafusada");
		roteiroMadAcoButton.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				roteiroMadAcoButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(layout.createSequentialGroup()
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(130, 130, 130).addComponent(jLabel1))
		                        .addGroup(layout.createSequentialGroup().addGap(101, 101, 101)
		                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                                        .addComponent(roteiroMadParaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                                        .addComponent(roteiroMadPreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                                        .addComponent(roteiroMadAcoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
		                .addContainerGap(102, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		        .addGroup(layout.createSequentialGroup().addGap(43, 43, 43).addComponent(jLabel1).addGap(34, 34, 34).addComponent(roteiroMadParaButton).addGap(41, 41, 41)
		                .addComponent(roteiroMadPreButton).addGap(37, 37, 37).addComponent(roteiroMadAcoButton).addContainerGap(61, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void roteiroMadParaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoteiroMadParaButtonActionPerformed
		if(!Desktop.isDesktopSupported()) {
			System.out.println("Desktop is not supported");
			return;
		}

		Desktop desktop = Desktop.getDesktop();

		//let's try to open PDF file
		String basePath = new File("").getAbsolutePath();
		System.out.println(basePath + "<-ESSE É O CAMINHO PARA O PROJETO");
		File file = new File(basePath + "\\ajuda/MadeiraMadeiraParafusos.pdf");
		if(file.exists()) {

			try {
				desktop.open(file);
			} catch (IOException ex) {
				Logger.getLogger(RoteirosDimensionamento.class.getName()).log(Level.SEVERE, null, ex);
			}
			System.out.println("SUCESSO!");
		}
	}//GEN-LAST:event_RoteiroMadParaButtonActionPerformed

	private void roteiroMadPreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoteiroMadPreButtonActionPerformed
		if(!Desktop.isDesktopSupported()) {
			System.out.println("Desktop is not supported");
			return;
		}

		Desktop desktop = Desktop.getDesktop();

		//let's try to open PDF file
		String basePath = new File("").getAbsolutePath();
		System.out.println(basePath + "<-ESSE É O CAMINHO PARA O PROJETO");
		File file = new File(basePath + "\\ajuda/MadeiraMadeiraPregos.pdf");
		if(file.exists()) {

			try {
				desktop.open(file);
			} catch (IOException ex) {
				Logger.getLogger(RoteirosDimensionamento.class.getName()).log(Level.SEVERE, null, ex);
			}
			System.out.println("SUCESSO!");
		}
	}//GEN-LAST:event_RoteiroMadPreButtonActionPerformed

	private void roteiroMadAcoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoteiroMadAcoButtonActionPerformed
		// TODO add your handling code here:
		if(!Desktop.isDesktopSupported()) {
			System.out.println("Desktop is not supported");
			return;
		}

		Desktop desktop = Desktop.getDesktop();

		//let's try to open PDF file
		String basePath = new File("").getAbsolutePath();
		System.out.println(basePath + "<-ESSE É O CAMINHO PARA O PROJETO");
		File file = new File(basePath + "\\ajuda/MadeiraAco.pdf");
		if(file.exists()) {

			try {
				desktop.open(file);
			} catch (IOException ex) {
				Logger.getLogger(RoteirosDimensionamento.class.getName()).log(Level.SEVERE, null, ex);
			}
			System.out.println("SUCESSO!");
		}
	}//GEN-LAST:event_RoteiroMadAcoButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		try {
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RoteirosDimensionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RoteirosDimensionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RoteirosDimensionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RoteirosDimensionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable(){
			public void run() {
				new RoteirosDimensionamento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton roteiroMadAcoButton;
	private javax.swing.JButton roteiroMadParaButton;
	private javax.swing.JButton roteiroMadPreButton;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
