/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcd.telas;

/**
 *
 * @author Gabriela Mello
 */
public class TelaInicial extends javax.swing.JFrame {

	private static final long serialVersionUID = -7502074505828048707L;

	/**
	 * Creates new form TelaInicial
	 */
	public TelaInicial() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jToggleButton1 = new javax.swing.JToggleButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(204, 255, 204));
		setMinimumSize(new java.awt.Dimension(910, 640));
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel2.setText("TCD - Timber Connections Design ");
		getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

		jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcd/ImagensBotao/DuasSecoesAcoForaPequeno.png"))); // NOI18N
		jButton1.setText("Madeira/Aço - Parafusada");
		jButton1.setToolTipText("Escolha esta opção se sua ligação for entre elementos de madeira e chapa de aço unidas por parafusos.");
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 250, 190));

		jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcd/ImagensBotao/Duas Seções ParafusoPequeno.png"))); // NOI18N
		jButton2.setText("Madeira/Madeira - Parafusada");
		jButton2.setToolTipText("Escolha esta opção se sua ligação for entre elementos de madeira e chapa de aço unidas por parafusos.");
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton2.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 190));
		getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

		jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel16.setText("Versão Educacional 2.0");
		getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 285, -1, -1));

		jToggleButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcd/ImagensBotao/DuasSecoesPregoPequeno.png"))); // NOI18N
		jToggleButton1.setText("Madeira/Madeira - Pregada");
		jToggleButton1.setToolTipText("Escolha esta opção se sua ligação for entre elementos de madeira e chapa de aço unidas por pregos.");
		jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton1.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 250, 190));

		jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 0, 204));
		jLabel3.setText("Sobre");
		jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter(){
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});
		getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

		jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 0, 204));
		jLabel4.setText("Ajuda");
		jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter(){
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}
		});
		getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcd/Logo/logosket.png"))); // NOI18N
		getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 340, 180));
		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		TelaAco telaAco = new TelaAco();
		telaAco.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		TelaParafuso telaPrincipal = new TelaParafuso();
		telaPrincipal.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
		TelaPrego telaprego = new TelaPrego();
		telaprego.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_jToggleButton1ActionPerformed

	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
		new TelaApresentacao().setVisible(true);
	}//GEN-LAST:event_jLabel3MouseClicked

	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
		AjudaNovo ajuda = new AjudaNovo();
		ajuda.setVisible(true);
	}//GEN-LAST:event_jLabel4MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		try {
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable(){
			public void run() {
				new TelaInicial().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JToggleButton jToggleButton1;
	// End of variables declaration//GEN-END:variables
}
